### ISSUE TITLE
Undefined behavior with the Bluetooth pairing

### ISSUE THREAD

**Issue by CoAuToSe** [robot-soccer-kit/robot-soccer-kit#54]
When connecting one of the robots with Bluetooth, the robot almost imediatly change from "connected" to "coupled". Therefore, we can't properly use the robots. The physical setup used is this [one](https://robot-soccer-kit.github.io/hardware-setup) and the software setup is this [one](https://robot-soccer-kit.github.io/install-windows/) (the software is working properly when the robot is "connected" but not "coupled"), meaning that it should be working but it doesn't... We got it working properly about 1 time out of 30 (mainly with a new computer each try but also rarely with one that was already used).

Also, when looking at the Device Manager, the robot is still in the Bluetooth device (even shutdown) and doesn't want to be deleted, but can be deleted when there are multiple robot. (example: I have "holo_6" in my list of Bluetooth devices but the robot "holo_6" is 2 km away from me and is not powered)

OS: Windows 10

**Comment by Gregwar** [comment]
Hello,

1. Is there internal Bluetooth in the computers you are using ?
2. If you want to delete a robot, can you try plugging the dongle you used for pair before clicking on "Delete" ?

I am not sure to understand what your problem actually is; do you mean that COM ports opening simply fails?

**Comment by CoAuToSe** [comment]
There is internal Bluetooth in the computers we use. We started using it because it was able to "work" but we bought a dongle and nothing changed when using it. 
We initially paired the robot with the Bluetooth of our computers and not with the dongle. When we tried to pair them with the dongle, we ran into the same issue. 

We can delete the COM ports as much as we want, but I think that the Bluetooth pairing is not working as intended in our case as. We can connect to the robots with Bluetooth without issue (creating the COM ports) but the connection seems to be unstable, usually ending in pairing and not conneting. And, therefore, not allowing us to use the robots.

**Comment by cgaspard3333** [comment]
Hello,

We are trying to understand your problem. 
Are you a student or a teacher participating to the RSK program in the "Académie de Bordeaux" ?

If so, we can help you with a TeamViewer assistance. 
We have the setup fully working with several Computers with Windows 10 and Windows 11 and no real pairing problem (most of the time this sort of problem apears on Linux)

However, using the internal Bluetooth is not really fonctionnal. For now, we strongly recommand to use a dongle. 
(It works well with the following dongle referenced in the documentation : ZEXMTE Adaptateur Bluetooth Usb 5.0)
By experiment, Realtek internal Bluetooth seems to work, but Intel is not working well.

Furthermore, **before plugging in the dongle** (and then use it), you have to first disable the internal Bluetooth adapter **in the Device Manager** and not in the Windows Settings interface. Then try to pair again the bots (even they already exist in the device manager)

**Comment by CoAuToSe** [comment]
Ok, so I resolved the problem that I was having but it came back later with the dongle, here is how I handled the issues:

1. First, I had the problem with the Bluetooth of the computer taking the lead over the dongle, which may create some Bluetooth ghost linked Robot (which can't be deleted). It was solved by disalbing the Bluetooth of the computer and then plugging in the dongle which may allow the ghost linked robots to be deleted. Otherwise it is the second problem that I resolved.

2. I ran into another problem when coming back to my "old" workspace, about one week without working with it. All the robot's Bluetooth links became ghost on the dongle's Bluetooth and didn't wanted to be deleted(even with the dongle plugged in in the right USB).
To resolve it, I came back to a fresh state of the computer that I was using. I tried deleting Bluetooth links as soon as possible (if u don't use the dongle it may not work, as tested) but there was one ghost robot remaining (and the game controller wasn't working as intended). I might have tried everything that would come to mind quickly to solve this issues.
The solution that I found was to unplug the dongle and reactivate my computer's Bluetooth followed by a restart of the computer (restarting without the computer's Bluetooth reactivated didn't solved the issue for us, shutting down and turning on the computer wasn't tested). Which allowed the deletion of the ghost robot when plugging the dongle (may require to be done "as fast as possible", otherwise you may need to restart "the whole solution"). Therefore it was as if I had never connected the robots to the computer. Following with the steps of the first issue, we currently have it working for us. (even if I had to wait more than a minute "in the void" for the robot to connect with the game controller, with the dongle plugged and a robot linked with the Blutooth)

I also recognised that the dongle may need to be plugged into a USB type charger(the one with the charger icon) of a laptop to have it working. The dongle's LED was blinking more when used this way, and I had more problems otherwise.

The process are long and may be shortened.

To clarify who I am, I am Aurelien from ESME.
